### ISSUE TITLE
after giving js file reference, build is getting failed 

### ISSUE THREAD

**Issue by pranshu89** [nico3333fr/van11y-accessible-accordion-aria#1]
Hi, I am using your accessible accordions, however my MVN build is getting failed every time , I am giving your JS file reference. Please see below, what I am doing:
 1. A JSP page where I am using accordion
2. Gave your js file reference in JSP page and I have added JS file in that location

And then I am building my app using MVN CLEAN INSTALL command and it is getting failed.

**Comment by nico3333fr** [comment]
Hi,

I don't know what occurs this problem. Gonna ask for help on Twitter.

**Comment by tipounet** [comment]
that they are the mistakes?

Maven filtering and replacement  ? 
https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html

**Comment by nico3333fr** [comment]
If you have any details, do not hesitate to reopen this issue.
