### ISSUE TITLE
Generated numerical ID invalid selector

### ISSUE THREAD

**Issue by brandlewco** [nico3333fr/van11y-accessible-accordion-aria#10]
I run into a problem where any ID for an accordion that starts with a number, like id="6rjsaq98q2" breaks when used. 

`Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#6rjsaq98q2[data-hashaccordion-id="k0vuv1jup0"]' is not a valid selector.`

No problem when generated ID starts with a letter.

**Comment by nico3333fr** [comment]
Fine, you bring me a solution for #9 ! 👍 

I'm committing a quick fix right now.

**Comment by nico3333fr** [comment]
Hi @lewcrewco 

the last commit fixed this issue, thanks again for your help https://github.com/nico3333fr/van11y-accessible-accordion-aria/commit/8a9b9815585c8646d0df06d779b9d76a1556a817 👍
