### ISSUE TITLE
Invoke programmatically

### ISSUE THREAD

**Issue by intelligence** [nico3333fr/van11y-accessible-accordion-aria#2]
Hey!

Nice accordion.
I'm using this on a project where I have transitions from page to page via pjax.
Thus I need to be able to initialize accordions when a page is fetched.

Any idea on how I can achieve this?

**Comment by nico3333fr** [comment]
Hi,

thanks for your suggestion. I'm doing some tests and updates to make it possible. ;)

**Comment by intelligence** [comment]
Awesome! Do you have any idea about an ETA?

**Comment by nico3333fr** [comment]
I can't promise anything, I hope to the end of this week, if everything goes fine.

**Comment by nico3333fr** [comment]
I can't promise anything, I hope to the end of this week, if everything goes fine.

**Comment by intelligence** [comment]
Oh no worries, was just curious if we were talking months, weeks or days :) 👍

**Comment by nico3333fr** [comment]
The last commit added it: https://github.com/nico3333fr/van11y-accessible-accordion-aria/commit/67ddda996c520735fcd90537a11dd1ca71c8a443 

```van11yAccessibleAccordionAria(document.getElementById('newContent'));```

**Comment by intelligence** [comment]
Awesome, thanks a lot!

Doesn't seem like latest update is available via npm, do you have to update something so it pulls the latest version?

**Comment by nico3333fr** [comment]
@intelligence my mistake, I forgot to update it yesterday. It is pushed, with a small update of documentation. https://www.npmjs.com/package/van11y-accessible-accordion-aria ;)

**Comment by intelligence** [comment]
Thanks for your prompt reply @nico3333fr!

I'm struggling with getting it to work though, can you maybe help out?
I'm importing your module like this:
`const van11yAccessibleAccordionAria = require('van11y-accessible-accordion-aria');
`

I'm then calling it on my accordion (that works just fine if ajax fetching is not enabled, so markup and everything is correct).
`van11yAccessibleAccordionAria(document.getElementById('accordion-subnavigation'));
` 

This renders the console output
```
Uncaught TypeError: van11yAccessibleAccordionAria is not a function
    at Object.onEnter (common.js:804)
    at Object.<anonymous> (barba.js:816)
    at Object.trigger (barba.js:929)
    at Object.init (barba.js:1151)
    at Object.start (barba.js:1129)
    at Object.finalize (common.js:1118)
    at Router.fire (Router.js:22)
    at Router.loadEvents (Router.js:42)
    at HTMLDocument.<anonymous> (main.js:25)
    at i (jquery-1.12.4.min.js:2)
```

**Comment by intelligence** [comment]
If I simply do
`import 'van11y-accessible-accordion-aria';`

And then run 
```
/* eslint-disable no-undef */
van11yAccessibleAccordionAria(document.getElementById('accordion-subnavigation'));
/* eslint-enable no-undef */
```

I get no error messages in the console, but no initialization either.

What am I doing wrong? :)

**Comment by intelligence** [comment]
Ah, sorry, didn't realize the div with the id should be wrapped around the elements. Works just fine now!

Thanks alot :)

**Comment by nico3333fr** [comment]
Yes, you found the solution before I was able to tell you, you're great 👍 

If you don't mind, I've mentionned you in the announcement: https://van11y.net/2017/10/15/Version-2-0-for-accordion-script

**Comment by Alhadis** [comment]
Any of you guys feel like offering some constructive criticism and thoughts on [my Accordion](https://github.com/Alhadis/Accordion)? 😉

It, uh, even supports IE8.

**Comment by nickpish** [comment]
Hi @nico3333fr - first off, thanks so much for this fantastic accordion library! I'm trying to get this working on a page that allows filtering content via Ajax, and thus reinitialize the accordions whenever the content refreshes. The filter plugin I'm using ([FacetWP](https://facetwp.com/)) provides an event, `facet-wp-loaded` that triggers when the content finishes refreshing, so I'm trying to re-initialize the accordions in this way, but I can't seem to get it working:

```
document.addEventListener("facetwp-loaded", function() {
    console.log('FWP loaded!');
    const accordion = new van11yAccessibleAccordionAria(document.getElementById('container'));
}, false);
```

I'm not sure if I'm invoking the accordion correctly or which container element I should initialize on, whether `.js-accordion` or one wrapping around that element? I've tried several, but none seem to work. Thank you for any assistance you're able to provide!

**Comment by nickpish** [comment]
For anyone who might be trying to achieve something similar to what I described above, I came up with a working solution using the following- note that in my case, the `facetwp-loaded` event runs on initial page load as well as after subsequent refreshes via Ajax, so I needed to ensure that the accordion wasn't already initialized by checking for the presence of the class with custom prefix (set via `data-accordion-prefix-classes="prefix"`) as follows:

```
document.addEventListener("facetwp-loaded", function() {
  const container = document.querySelector("#container .js-accordion");
  if (!container.classList.contains("prefix-accordion") {
    // console.log('accordion NOT already initialized - now initializing!');
    const accordion = van11yAccessibleAccordionAria(document.getElementById('container'));
    accordion.attach();
  }
}, false);
```

There's likely a better way to do this, but it seems to work!
