### ISSUE TITLE
Combine tabs and accordion

### ISSUE THREAD

**Issue by evanre** [nico3333fr/van11y-accessible-accordion-aria#5]
Hi, first of all I would like to thank you for this 'a11y' - treasures. This plugins looks wonderful!

I have a question. Is there a way to combine your tabs and accordion plugins into one? I need to create an ARIA ready tabs panel which transforms into accordion on smaller screens.

**Comment by nico3333fr** [comment]
Hi @evanre,

we have two options: 
- you wait for a rewrite on tab script, that will allow adding new methods (destroy/etc.) that will allow do to this properly (it will come, but will take some time ;) )
- there is a way to do it combining hide/show https://van11y.net/accessible-hide-show/ and tabs.

Here is the trick:
You use the tabs script, and in each tab content, you use hide/show. On desktop version, you hide the hide/show buttons and always display hide/show contents, and on mobile version, you hide tab buttons and show expands normally.

You may see an example here: https://directory.esomar.org/ (see "Codes & Guidelines" tabs at the bottom).

Do you understand how to do it? If not, I will add an example on Van11y website.

**Comment by evanre** [comment]
Hello, @nico3333fr.
Thanks for the lead, it's enough for me at the moment. 
But if you'll add some example, it would be great =) I found examples on w3c website ([acordion](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/accordion/accordion.html), [tabs](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/tabs/tabs-1/tabs.html)) But I don't know how to marge them and make correct from the a11y point of view.

PS. Also I would be glad to see new features in your plugins! Start watching them!

**Comment by nico3333fr** [comment]
I close this question. ;)
