### ISSUE TITLE
"Uncaught DOMException: Failed to execute 'querySelector'" error

### ISSUE THREAD

**Issue by CharlotteCMJ** [nico3333fr/van11y-accessible-accordion-aria#9]
Hi,
I am using the latest version (3.0) of this accessible accordion and there is apparently an issue with the `data-hashaccordion-id`. When I click on the accordion, sometimes the accordion won't open and the console throws the following error: 

`Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#86gigjp0th[data-hashaccordion-id="lhcov0q06c"]' is not a valid selector.`

I ran into this error in my project as well as on the demo page.

### Steps to reproduce: 
On the  [demo page](https://van11y.net/downloads/accordion/demo/index.html), click on the first accordion (on any of the headers).
If the accordion opens properly, refresh the page and try again.

Is it possible to fix this?
Thank you in advance

**Comment by nico3333fr** [comment]
Hi,

I had this bug while developing, I though it was fixed... I'll have a look asap ;)

**Comment by nico3333fr** [comment]
Hi @CharlotteCMJ, it has been fixed thanks to @lewcrewco comment in #10.

The last commit has fixed this problem https://github.com/nico3333fr/van11y-accessible-accordion-aria/commit/8a9b9815585c8646d0df06d779b9d76a1556a817 

Thanks for reporting this problem 👍
